In [ ]:
import numpy as np

## This a 1 dimentional array 
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [4]:
print(type(arr))

<class 'numpy.ndarray'>


In [6]:
arr1 = np.array((1, 2, 3, 4, 5, 6))
print(arr1)
print(type(arr1))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


### 0D array
###### *Each value in an array is a 0-D array*

In [23]:
Arr = np.array(42)
print(Arr)
print(Arr.ndim)

42
0


### 1D array
###### *An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.*

In [ ]:
arr2 = np.array([1,2,3,4,5,6])
print(arr2)
print(arr2.ndim)
print(arr2[3]) #? Indexing
print(arr2[1:5]) # Slicing An array from 1st index to 2nd index
print(arr2[1:]) # Slicing array from 1st index to lentgh of the array
print(arr2[:2]) # Slicing array from start to 2nd index
print(arr2[:]) # Slicing array from start to end with lenth of array


[1 2 3 4 5 6]
1
4
[2 3 4 5]
[2 3 4 5 6]
[1 2]
[1 2 3 4 5 6]


### 2-D Arrays
###### *An array that has 1-D arrays as its elements is called a 2-D array.*
###### *These are often used to represent matrix or 2nd order tensors.*

In [84]:
arr3 = np.array([[1,2,3],[4,5,6]])
print(arr3)
print(arr3.ndim)
print(arr3[1,2])
print(arr3[0, 0:2]) # slicing value from 1st element and the start and end 
print(arr3.shape)

[[1 2 3]
 [4 5 6]]
2
6
[1 2]
(2, 3)


### 3-D arrays
###### *An array that has 2-D arrays (matrices) as its elements is called 3-D array.*

###### *These are often used to represent a 3rd order tensor.*

In [83]:
arr4 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[3,2,1]]])
print(arr4)
print(arr4.ndim)
print(arr4[1,0,2])
print(arr4.shape)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [3 2 1]]]
3
9
(2, 2, 3)


In [21]:
arr = np.array([1,2,3,4], ndmin=4)
print(arr)
print(arr.ndim)

[[[[1 2 3 4]]]]
4


In [63]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])
print(arr[::2])

[10 20 30 40]


### Data Types in NumPy
###### NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.
###### Below is a list of all data types in NumPy and the characters used to represent them.
- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string
- V - fixed chunk of memory for other type ( void )

In [64]:
arr = np.array([1,2,3,4,5])
print(arr.dtype)

int64


In [65]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


In [ ]:
arr = np.array([1,2,3,4,5], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S5


### NumPy Array Copy vs View

In [79]:
# Copy
arr = np.array([1,2,3,4,5,6])
x = arr.copy()
arr[0] = 42
print(x)
print(x.dtype)
print(arr)
print(arr.dtype)
print(arr.base)


[1 2 3 4 5 6]
int64
[42  2  3  4  5  6]
int64
None


In [81]:
# view
arr = np.array([1,2,3,4,5,6])
x = arr.view()
arr[0] = 42
print(x)
print(x.dtype)
print(arr)
print(arr.dtype)
print(x.base)


[42  2  3  4  5  6]
int64
[42  2  3  4  5  6]
int64
[42  2  3  4  5  6]


In [77]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


#### Array Reshaping


In [98]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr1 = np.array([1,2,3,4,5,6,7,8])
arr2 = arr.reshape(3,3) # Reshap the array 1D to 2D
arr3 = arr1.reshape(2,2,2)
print(arr)
print(arr2)
print(arr3)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Iterating

###### **If we iterate on a n-D array it will go through n-1th dimension one by one.**
###### **like if there is an 2D array it ittarates in 1D**


In [101]:
arr3 = np.array([[1,2,3],[4,5,6]])
for x in arr3:
    print (x)

[1 2 3]
[4 5 6]


In [102]:
# ittereate on each element
arr3 = np.array([[1,2,3],[4,5,6]])
for x in arr3:
    for y in x:
        print (y)

1
2
3
4
5
6


In [110]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
# for x in arr:
#     print(x)

for x in np.nditer(arr):
    print(x)            

1
2
3
4
5
6
7
8
9
10
11
12


#### Joining Array


In [114]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

arr = np.concatenate((arr1,arr2),axis=0)
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [124]:
arr1 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr2 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

arr = np.concatenate((arr1,arr2), axis = 0)
arr3 = np.concatenate((arr1,arr2), axis = 1)
arr4 = np.concatenate((arr1,arr2), axis = 2)

# print(arr)
print(arr3)
print(arr4)

[[[ 1  2  3]
  [ 4  5  6]
  [ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]
  [ 7  8  9]
  [10 11 12]]]
[[[ 1  2  3  1  2  3]
  [ 4  5  6  4  5  6]]

 [[ 7  8  9  7  8  9]
  [10 11 12 10 11 12]]]


### Splitting Array

In [129]:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3)
newarr1 = np.array_split(arr,4) # if array hase less element than required i will adgest accordingly
print(newarr)
print(newarr1)
print(newarr[0])
print(newarr[1])
print(newarr[2])

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4]), array([5]), array([6])]
[1 2]
[3 4]
[5 6]


In [144]:
# 2D arrays
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr,3, axis=0)
newarr1 = np.array_split(arr,2, axis=1)
print(newarr)
print(newarr1)
print(arr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]
[array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]])]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


#### Searching Arrays


In [149]:
arr = np.array([1,2,3,4,5,6,4])
x = np.where(arr == 4)
print(x)

(array([3, 6]),)


##### Search Sorted

###### The searchsorted() method is assumed to be used on sorted arrays.

In [ ]:
arr = np.array([1,2,3])
print(x)
x = np.searchsorted(arr,3)

# sort o=unorderd array and find the index
arr1 = np.array([4,3,6,5,8,1,3])
y = np.sort(arr1)
z = np.searchsorted(y,4)
print(y)
print(z)

2
[1 3 3 4 5 6 8]
3


In [ ]:
# Find the indexes where the values 2, 4, and 6 should be inserted:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])
print(x)

[1 2 3]


#### Sorting Arrays

In [159]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [ ]:
# soring a 2D array
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


#### Filter Array

In [ ]:
arr = np.array([12,43,65,22,98,43,11,45])
# method 01
filter_arr = []

for elements in arr:
    if elements >30:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

# method 02
filter_arr1 = arr >30
newarr1 = arr[filter_arr1]
print(newarr1)

[False, True, True, False, True, True, False, True]
[43 65 98 43 45]
[43 65 98 43 45]


In [166]:
arr = np.array([12,11,43,54,70,20])

filter_arr = []

for element in arr :
    if element % 2 == 0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)

x = arr[filter_arr]

print(x)


filter_arr1 = arr % 2 == 0

newarr = arr[filter_arr1]

print(filter_arr1)
print(newarr)

[12 54 70 20]
[ True False False  True  True  True]
[12 54 70 20]
