### Random Numbers in NumPy

In [99]:
import numpy as np
from numpy import random

In [ ]:
# Generate a random integer from 0 to 100
x = random.randint(100)
print(x)

69


In [89]:
# Generate a random float from 0 to 1
x = random.rand()
print(x)

0.7180558074655287


In [71]:
# Generate a 1-D array containing 9 random integers from 0 to 100
x = random.randint(100, size=(9))
print(x)

[52 49 95 22 99 82 37 32 28]


In [73]:
# Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100
x = random.randint(100, size=(3,5))
print(x)

[[29 72 94 82 52]
 [85 43 15 68 10]
 [31 18 21 98 58]]


In [91]:
x = random.rand(5)
print(x)

[0.72303103 0.55702037 0.14464589 0.19240048 0.67517575]


In [93]:
x = random.rand(3,5)
print(x)

[[0.98329227 0.48917821 0.26609685 0.44459182 0.26719555]
 [0.092407   0.29253555 0.64419913 0.074209   0.66463027]
 [0.92041461 0.78769653 0.21330541 0.01875063 0.37334692]]


In [94]:
x = random.choice([2,5,6,8])
print(x)

5


In [95]:
x = random.choice([2,5,6,8],size=(3,2))
print(x)

[[5 6]
 [2 5]
 [8 6]]


#### Random Data Distribution

In [98]:
x = random.choice([3,5,7,9], p=(0.15,0.3,0.3,0.25), size=(100))
print(x)

[5 9 3 3 5 3 3 9 9 3 9 9 5 7 9 9 5 9 7 5 3 3 7 9 9 7 7 7 3 7 5 3 7 7 9 5 3
 5 3 5 5 9 5 5 7 5 7 7 7 7 7 3 7 5 9 5 5 7 3 7 9 5 7 7 5 7 7 7 9 3 5 3 9 3
 9 5 9 7 3 5 7 5 9 7 9 9 9 9 7 9 9 7 5 5 7 5 9 9 5 7]


#### Random Permutations


In [ ]:
# The shuffle() method makes changes to the original array.
x = np.array([1,2,3,4,5])
random.shuffle(x)
print(x)

[2 1 4 3 5]


In [ ]:
# The permutation() method returns a re-arranged array (and leaves the original array un-changed).
x = np.array([1,2,3,4,5])
print(random.permutation(x))

[1 2 3 4 5]
